sudo: false
language: node_js
node_js:
  - '10'
cache:
  directories:
    - '$HOME/.npm'
    - node_modules
jobs:
  include:
    - stage: test
      script: yarn test
    - stage: release
      if: branch = master
      # script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - yarn build
          - yarn semantic-release
          - yarn test:coverage:send
