sudo: false
language: node_js
node_js:
  - '10'
cache:
  directories:
    - '$HOME/.npm'
jobs:
  include:
    - stage: install
      script: yarn install
      skip_cleanup: true
    - stage: test
      script:
        - yarn test
      skip_cleanup: true
    - stage: release
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
        after_success:
          - yarn test:coverage:send
      if: branch = master
