on:
  push:
    branches:
      - develop
name: Auto PR from Develop → Master
jobs:
  createNewPullRequest:
    name: Create New Develop → Master PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Create New Pull Request
        uses: vsoch/pull-request-action@master
        env:
          BRANCH_PREFIX: develop
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_REQUEST_BRANCH: master
